local M = {}

function M.get(c, _)
	return {
		TroubleNormal = { bg = c.base.black, fg = c.base.white },
		TroubleNormalNC = { bg = c.base.black, fg = c.base.dimmed1 },
		TroubleText = { fg = c.base.white },
		TroubleTextInformation = { fg = c.base.cyan },
		TroubleTextWarning = { fg = c.base.yellow },
		TroubleTextError = { fg = c.base.red },
		TroubleTextHint = { fg = c.base.green },
		TroubleCount = { fg = c.base.dimmed1, bg = c.base.dimmed5 },
		TroubleLocation = { fg = c.base.dimmed2 },
		TroubleFilename = { fg = c.base.cyan, bold = true },
		TroubleDirectory = { fg = c.base.dimmed3 },
		TroubleCode = { fg = c.base.magenta },
		TroubleSource = { fg = c.base.dimmed3 },
		TroubleIndent = { fg = c.base.dimmed5 },
		TroubleIndentFoldClosed = { fg = c.base.dimmed2 },
		TroubleIndentFoldOpen = { fg = c.base.dimmed2 },
		TroubleFoldIcon = { fg = c.base.dimmed2 },
		TroubleFoldIconClosed = { fg = c.base.yellow },
		TroubleFoldIconOpen = { fg = c.base.green },
		TroublePreview = { bg = c.base.dimmed5 },
		TroubleSignError = { fg = c.base.red },
		TroubleSignWarning = { fg = c.base.yellow },
		TroubleSignInformation = { fg = c.base.cyan },
		TroubleSignHint = { fg = c.base.green },
		TroubleSignOther = { fg = c.base.magenta },
		TroubleIconArray = { fg = c.base.blue },
		TroubleIconBoolean = { fg = c.base.blue },
		TroubleIconClass = { fg = c.base.yellow },
		TroubleIconConstant = { fg = c.base.magenta },
		TroubleIconConstructor = { fg = c.base.green },
		TroubleIconEnum = { fg = c.base.yellow },
		TroubleIconEnumMember = { fg = c.base.cyan },
		TroubleIconEvent = { fg = c.base.blue },
		TroubleIconField = { fg = c.base.cyan },
		TroubleIconFile = { fg = c.base.cyan },
		TroubleIconFunction = { fg = c.base.green },
		TroubleIconInterface = { fg = c.base.cyan },
		TroubleIconKey = { fg = c.base.magenta },
		TroubleIconMethod = { fg = c.base.green },
		TroubleIconModule = { fg = c.base.yellow },
		TroubleIconNamespace = { fg = c.base.yellow },
		TroubleIconNull = { fg = c.base.dimmed2 },
		TroubleIconNumber = { fg = c.base.magenta },
		TroubleIconObject = { fg = c.base.yellow },
		TroubleIconOperator = { fg = c.base.red },
		TroubleIconPackage = { fg = c.base.yellow },
		TroubleIconProperty = { fg = c.base.cyan },
		TroubleIconString = { fg = c.base.yellow },
		TroubleIconStruct = { fg = c.base.cyan },
		TroubleIconTypeParameter = { fg = c.base.blue },
		TroubleIconVariable = { fg = c.base.white },
	}
end

return M
