#!/usr/bin/env bash
#
# Generate theme configuration files based on BAKED_THEME environment variable
# This script is called automatically on shell initialization

set -euo pipefail

# Default theme if not set
THEME="${BAKED_THEME:-monokai}"

# Dotfiles directory
DOTFILES="${HOME}/.dotfiles"

# Validate theme
if [[ "$THEME" != "monokai" && "$THEME" != "onedark" && "$THEME" != "catppuccin" && "$THEME" != "tokyonight" && "$THEME" != "rosepine" ]]; then
  echo "Warning: Invalid BAKED_THEME '$THEME'. Using 'monokai'." >&2
  THEME="monokai"
fi

# Generate Ghostty theme config
generate_ghostty_config() {
  local ghostty_dir="${DOTFILES}/ghostty/.config/ghostty"
  local output="${ghostty_dir}/active-theme.conf"
  
  mkdir -p "$ghostty_dir"
  
  cat > "$output" << EOF
# Auto-generated by ${DOTFILES}/colors/generate-themes.sh
# Do not edit manually - changes will be overwritten
# Theme: baked-${THEME}

theme = baked-${THEME}
EOF
}

# Generate Tmux theme config
generate_tmux_config() {
  local output="${DOTFILES}/tmux/active-theme.conf"
  
  mkdir -p "${DOTFILES}/tmux"
  
  cat > "$output" << 'EOF'
# Auto-generated by ~/.dotfiles/colors/generate-themes.sh
# Do not edit manually - changes will be overwritten
#
# Tmux uses ANSI color names which automatically match the terminal's palette
# No theme-specific configuration needed - colors are inherited from Ghostty
EOF
}

# Generate OpenCode config
generate_opencode_config() {
  local opencode_dir="${DOTFILES}/opencode/.config/opencode"
  local template="${opencode_dir}/opencode.json.template"
  local output="${opencode_dir}/opencode.json"
  
  if [[ ! -f "$template" ]]; then
    echo "Warning: OpenCode template not found at $template" >&2
    return 1
  fi
  
  mkdir -p "$opencode_dir"
  
  # Replace __THEME__ placeholder with actual theme
  sed "s/__THEME__/${THEME}/g" "$template" > "$output"
}

# Generate FZF theme config
generate_fzf_config() {
  local output="${DOTFILES}/zsh/fzf-theme.zsh"
  
  mkdir -p "${DOTFILES}/zsh"
  
  # Generate FZF color configuration using ANSI color names
  # FZF automatically picks up colors from the terminal's palette
  cat > "$output" << 'EOF'
# Auto-generated by ~/.dotfiles/colors/generate-themes.sh
# Do not edit manually - changes will be overwritten
# FZF uses ANSI color names which automatically match the terminal's palette

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --color=fg:white,bg:black,hl:cyan --color=fg+:white,bg+:black,hl+:cyan --color=info:green,prompt:red,pointer:yellow --color=marker:green,spinner:magenta,header:yellow'
EOF
}

# Main execution
generate_ghostty_config
generate_tmux_config
generate_opencode_config
generate_fzf_config
